### ISSUE TITLE
Having trouble setting pose transform.

### ISSUE THREAD

**Issue by rnunziata** [cvlab-dresden/DSAC#10]
I want to publish a pose transform using the estimate from test_ransac. I have the following but the results I get is not correct.  The pose jumps around , am I setting the fields incorrectly?

```
        tf::Matrix3x3 M(hypR.at<float>(0,0),hypR.at<float>(0,1),hypR.at<float>(0,2),
                        hypR.at<float>(1,0),hypR.at<float>(1,1),hypR.at<float>(1,2),
                        hypR.at<float>(2,0),hypR.at<float>(2,1),hypR.at<float>(2,2));
        tf::Quaternion q;
        M.getRotation(q); 
        tf::Vector3 t(hypV[3], hypV[4],  hypV[5] );    
        tf::Transform filtered;
        filtered.setOrigin(t);
        filtered.setRotation(q);
```
camera rgb calibration: for image stream
The color images 640×480 
```
fx | fy | cx | cy | d0 | d1 | d2 | d3 | d4
520.9 | 521.0 | 325.1 | 249.7 | 0.2312 | -0.7849 | -0.0033 | -0.0001 | 0.9172
```

**Comment by ebrach** [comment]
Make sure you read out the pose estimation after line 188, because it is inverted before this line.
Also, I think hypR is a double matrix.

One way to debug this is to work with ground truth poses first. If you manage to transform them to your data format, you should also be able to do it for the DSAC estimates.
