### ISSUE TITLE
About settings in CmakeList

### ISSUE THREAD

**Issue by yuzheyyyy** [cvlab-dresden/DSAC#16]
In CmakeList, I have set LUA and Torch's new locations. But for somewhere, like
`target_link_libraries(train_obj ${PNG_LIBRARY} ${OpenCV_LIBS} ${luajit}) 
target_link_libraries(train_score ${PNG_LIBRARY} ${OpenCV_LIBS} ${luajit})
target_link_libraries(test_ransac ${PNG_LIBRARY} ${OpenCV_LIBS} ${luajit})
target_link_libraries(train_ransac ${PNG_LIBRARY} ${OpenCV_LIBS} ${luajit})
target_link_libraries(test_ransac_softam ${PNG_LIBRARY} ${OpenCV_LIBS} ${luajit})
target_link_libraries(train_ransac_softam ${PNG_LIBRARY} ${OpenCV_LIBS} ${luajit})`

I don't know how to set them,
I try to add senctence like `set(luajit /home/open/torch/install/lib/libluajit.so) `
but when in making, it seems to show errors, like **'undefined reference to `lua_createtable''**
when I don't do anything, it seems to show the same error.
However, when I try to set things like 'set (luajit .././liblua.so)' it seems to make successfully, but when doing experiment, something goes wrong, like **'error loading module 'libpaths' from file'...**
Could u tell me how to set the Cmake, or is there something wrong with my environment settings.
The environment setting is :CUDA8.0, CUDNN5.0, TORCH7, OPENCV2.4,PNG1.2.53,LUA5.3

**Comment by ebrach** [comment]
Hi,

"luajit" is not the name of a variable but the name of a library. The corresponding lines should read:
 
target_link_libraries(train_obj ${PNG_LIBRARY} ${OpenCV_LIBS} luajit)

In order for this to work, the luajit library has to be in a path that is scanned by your linker, via "link_directories(...)". If the juajit lib lies in your torch install folder (as suggested by your post) it should work with the cmake file in the repo, since it adds the library folder of torch.

Hope that helps,
Eric
