### ISSUE TITLE
DSAC——test_

### ISSUE THREAD

**Issue by hm510** [cvlab-dresden/DSAC#17]
hi eric,
i try to test the dsac results by using your code and your trained model. but when i test the code of dsac, i found out the "Sampling  hypotheses" step of processImage function in cnn.h fall into a endless for loop due to it can't safasolve the pnp.
How can i fix it?
![issue_dsac](https://user-images.githubusercontent.com/23427268/79546187-9336aa00-80c4-11ea-9ea7-cffed78ac4ff.png)

**Comment by hm510** [comment]
i found out it is the problem about the luajit, now i fixed. thanks for your work

**Comment by ghPak1002** [comment]
Hello hm510.
I face the same problem as you said. Could I ask the solution of this problem?

**Comment by ebrach** [comment]
Hi, 
RANSAC sampling getting stuck is often caused by degenerate network predictions. The LUA script probably threw an error that the C++ framework did not catch. You can debug by e.g. adding console outputs throughout the LUA script to see whether it actually runs through. 

As hm510 also found out, there is probably something wrong with the LUA installation on your machine. 

Best,
Eric

(If there is no particular reason that you want to try this version of DSAC, I advice to switch to DSAC++ or DSAC* instead that replaced LUA/Torch with PyTorch. https://github.com/vislearn/LessMore or https://github.com/vislearn/dsacstar)

**Comment by ghPak1002** [comment]
Hi,
Thanks for your pleasure:)
I would switch the other DSAC++ or DSAC*.

**Comment by abirbensoltane** [comment]
> Hi!how do you solve this problem? @ghPak1002 @hm510
Hi ,@ebrach. Even in DSAC++ i have to install torch and lua and I run into the same prob!

**Comment by ebrach** [comment]
Yes, you are right, DSAC++ is based on LUA/Torch as well - I mixed it up, sorry! DSAC*, however, is indeed PyTorch-based and should be easier to handle nowadays. https://github.com/vislearn/dsacstar

If DSAC* is not an option I would, as advised above, add debugging break points in the LUA script to see where it gets stuck. An easy way of achieving something similar is to add console outputs to different stages in the LUA script to see what parts of the code actually get processed.

The underlying problem here is that any errors caused by LUA will not be recognised by the C++ side, due to my sloppy programming. Usually, there is some general problem with the LUA installation. Can you execute toy example LUA scripts on your machine? And can you call LUA from a C++ toy program?

Best,
Eric

**Comment by abirbensoltane** [comment]
@ebrach I tried to make breaking points waht i figure out so far is that it get stuck in the optional subsampling of images in the train_obj 
and i'm still trying to know why! 
I can execute lua script but i don't try to call it from a c++ program! I'll try it
