### ISSUE TITLE
Can dsac be speed up.

### ISSUE THREAD

**Issue by rnunziata** [cvlab-dresden/DSAC#9]
Right now it takes about over 1 sec per image.  Is there are way to speed it up.  Is the code enabled for GPU?

```
TORCH: Doing a forward pass for 1600 patches.
CNN prediction took 0.58221s.
Sampling 256 hypotheses.
Done in 0.963589s.
Calculating scores.
TORCH: Doing a forward pass for 256 images.
Done in 0.0349079s.
Drawing final Hypothesis.
Done in 8.1989e-05s.
Refining poses:
Done in 0.00228846s.
Final Result:

```

**Comment by ebrach** [comment]
Scene coordinate regression happens on the GPU, pose optimization happens on the CPU. This is research code, and many things could be made faster. But this is up to your own engineering efforts. Some suggestions:

-More efficient network architecture
-More efficient data transfer between LUA and C++ (or get rid of LUA altogether)
-Streamline test_ransac, because it still performs many calculations for the training phase
-Implement the pose optimization on GPU
